name: blurbattle
version: '1.0.0'
main: org.neo.blurbattle.Blurbattle
api-version: '1.21'
commands:
  blurbattle:
    description: Challenge another player to a PvP battle.
    usage: /blurbattle [player] or /blurbattle confirm
