name: Blurbattle
version: 1.0.1
main: org.neo.blurbattle.Blurbattle
api-version: 1.13
depend: ['Multiverse-Core']
commands:
  blurbattle:
    description: Challenge another player to a PvP battle.
    usage: /blurbattle <player> or /blurbattle confirm
    aliases: [ pvp ]
    permission: blurbattle.battle.command
    permission-message: you don't have permission to pvp, if you think this is an issue, contact the server admin
permissions:
  blurbattle.battle.command:
    description: Allows usage of the /blurbattle command
    default: true
